# ==============================================================
# WAX CONFIGURATION
# ==============================================================
# Jekyll configuration files are written in YAML format.
# Colons, tabs/spacing, and quotes are meaningful in YAML.
# It is recommended you look at the following guide to avoid
# syntax errors in this file:
# ~> https://learnxinyminutes.com/docs/yaml/
#
#
# Questions ?
# ~> https://minicomp.github.io/wiki/#/
# ~> https://gitter.im/minicomp/wax/
#
# ---------------------------------------------------------------
# MAIN SETTINGS
# ---------------------------------------------------------------
# Feel free to change these! For more info, refer to:
# ~> https://jekyllrb.com/docs/configuration/options/

title: "Literary AI"
description: "Lorem ipsum"
url: ""
baseurl: "/litai"
copyright: "Copyright 2021, Columbia University Libraries. Contents offered with a CC-BY 4.0 International License"
logo: "/assets/logo.png"

# ---------------------------------------------------------------
# BUILD SETTINGS
# ---------------------------------------------------------------
# Best not to mess with these unless you know what you're doing!

permalink: "pretty"
sass:
  style: compressed
exclude:
  - Gemfile*
  - Rakefile
  - vendor
  - spec
  - README.md
incremental: false
webrick:
  headers:
    "Access-Control-Allow-Origin": "*"
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# --------------------------------------------------------------
# COLLECTION SETTINGS
# --------------------------------------------------------------
# Wax leverages Jekyll collections for much of its
# functionality, therefor some of the keys below are from
# Jekyll while others are Wax-specific.
# For more info, refer to:
# ~> https://jekyllrb.com/docs/collections/

collections:
  exhibits:
    output: true
  projects:
    output: true
    layout: "projects" # the layout for the pages to use
    metadata:
      source: "projects.csv" # path to the metadata file within `_data`
    images:
      source: "raw_images/projects"
  cases:
    output: true
    layout: "case" # the layout for the pages to use
    metadata:
      source: "cases.csv" # path to the metadata file within `_data`
    images:
      source: "raw_images/cases"
  litai: # name of collection
    output: true # makes sure pages are output as html files
    layout: "litai_item" # the layout for the pages to use
    metadata:
      source: "litai.csv" # path to the metadata file within `_data`
    images:
      source: "raw_images/litai" # path to the directory of images within `_data`

# --------------------------------------------------------------
# SITE MENU SETTINGS
# --------------------------------------------------------------
# Each menu item needs a `label` (whats shown), and a `link`
# (where it goes). An item can optionally have a dropdown
# submenu via `sub`.

menu:
  - label: "About"
    sub:
      - label: "Credits"
        link: "/credits/"
  - label: "Projects"
    sub:
      - label: "First Year"
        link: "/first"
      - label: "[Dennis's Essay]"
        link: "#"
    #   - label: "Second Class"
    #     link: "#"

  - label: "Exhibit"
    sub:
      - label: "Case No. 1"
        link: "/case/1/"
      - label: "Case No. 2"
        link: "/case/2/"
      - label: "Case No. 3"
        link: "/case/3/"
      - label: "Case No. 4"
        link: "/case/4/"
      - label: "Case No. 5"
        link: "/case/5/"
      - label: "Case No. 6"
        link: "/case/6/"
      - label: "Case No. 7"
        link: "/case/7/"
      - label: "Case No. 8"
        link: "/case/8/"

# --------------------------------------------------------------
# SITE FOOTER SETTINGS
# --------------------------------------------------------------
#

footer:
  links:
    - label: "GitHub"
      link: "https://github.com/cul/"
    - label: "Contact"
      link: "mailto:agil@columbia.edu"
  logos:
    - img: "/img/logo.png"
# FIN
